const messages={
    USER_NOT_FOUND:"User not found",
    ADMIN_NOT_FOUND:"admin not found",
    LOG_IN:"User login successfully",
    VERIFIED:"user alredy vaerified",
    SIGN_UP:"User signup successfully",
    ADMIN_LOG_IN:"Admin log in successfull",
    SOMETHING_WRONG:"Something went wrong",
    OTP_VERIFY:"OTP verify successfull",
    OTP_NOT_VERIFY:"Please verify OTP",
    OTP_EXPIRED:"OTP time expired",
    WRONG_OTP:"OTP not match",
    DATA_NOT_FOUND:" data not found ",
    DATA_EDIT:"data edit successfully",
    EMAIL_PASSWORD:"email password does not valid",
    RESEND_OTP:"OTP resend successfully send on eamil",
    FORGOT_PASSWORD:"OTP successfully send on eamil",
    RESET_PASSWORD:"Password reset successfull",
    ALREDY_EXIST:"data alredy exist",
    PASSWORD_NOT_MATCH:"Password and  Confirmpassword not match",
    SKILL_ADD:"skill add successfullty",
    JOB_PLAN_ADD:"job plan add succesfully",
    PASSWORD_INVALID:"Password not match",
    CHANGE_PASSWORD:"Password change successfully",
    BOTH_FIELDS_REQUIRED:"Both fields are require",
    NUMBER_ALREDY_EXIST:"Mobile number already exist",
    MAIL_ALREADY_EXIST:"Email is already exist",
    USER_ALREADY:"User already exist",
    UNABLE_LOGIN:"Unable to login",
    EDIT_PROFILE:"Profile edit successfull",
    VIEW:"Profile view successfully",
    LIST:"User list successfull",
    DATA_VIEW:"User data view successfully",
    DELETE:"User delete successfull",
    BLOCK:"User block successfully",
    STATIC_VIEW:"View static data successfully",
    STATIC_ADD:"Add static data successfully",
    STATIC_LIST:"Static list successfully",
    WRONG:"Wrong email",
    COMPANY_ADD:"company add sucessfully",
    PRODUCT_ADD:"product add sucesfully",
    CUSTOMER_ADD: "customer add successfully",
    CUSTOMER_BLOCK:"customer block successfully",
     }
    module.exports=messages